ollama:
  url: http://127.0.0.1:11434/api/generate
  base_url: http://localhost:11434
  model: llama3.1:latest
  models:
    model1: llama3.1:latest
    model2: codestral:latest
    model3: deepseek-coder-v2:latest
    model4: gemma2:latest
    model5: dolphin-mixtral

ratatoskr:
  index: ratatoskr

elastic:
  http_auth:
    - "elastic"
    - "password"
  hosts: https://elasticsearch:9200

files:
  upload: /upload

rag_database:
  index: rag_documents