[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ratatoskr"
version = "0.1.0"
dependencies = []  # List your project's dependencies here

[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy", "black", "isort"]  # Dev dependencies
